version: "3.8"
services:
    nistagram-user-microservice:
      build: 
        context: .
        dockerfile: Dockerfile
        target: nistagramUserMicroserviceTest
      command: bash -c "mvn -B verify -P${STAGE} sonar:sonar -P${STAGE} -Dsonar.projectKey=${SONAR_PROJ_KEY_SVC} -Dsonar.organization=${SONARCLOUD_ORGANIZATION} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch.name=${BRANCH_NAME} -Dsonar.pullrequest.key=${PULL_KEY} -Dsonar.pullrequest.branch=${PULL_REQUEST_BRANCH} -Dsonar.pullrequest.base=${BASE}"
      container_name: nistagram-user
      ports:
        - 8080:8080


